.PHONY: all help clean push test build

export VERSION = 1.1.0.pre.1
export AWS_DEFAULT_REGION = us-east-1

define AWS_CLI_CMD
    docker container run --rm -i \
      -e AWS_ACCESS_KEY_ID       \
      -e AWS_DEFAULT_REGION      \
      -e AWS_SECRET_ACCESS_KEY   \
      -e AWS_SESSION_TOKEN       \
      redbubble/debian-awscli:master
endef

build: ## Create the docker image.
	@echo "--- :wind_chime: Building :wind_chime:"
	docker run \
		--rm \
		--workdir=/app \
		-v `pwd`:/app \
		-e VERSION \
		ruby:2.5 \
		gem build fluent-plugin-annotation-filter.gemspec

test: ## Run the app tests.
	@echo "--- :fire: Testing :fire:"
	docker run \
		--rm \
		--workdir=/app \
		-v `pwd`:/app \
		-e VERSION \
		-e BUNDLE_PATH=/app/gems \
		ruby:2.5 \
		script/docker-rspec.sh

push: build ## Publish the gem
	@echo "--- :fire: Pushing! :fire:"
	docker run \
		--rm \
		--workdir=/app \
		-v `pwd`:/app \
		-e VERSION \
		-e BUNDLE_PATH=/app/gems \
		-e GEM_HOST_API_KEY=$$(${AWS_CLI_CMD} aws secretsmanager get-secret-value --secret-id rubygems_api_key | jq '.SecretString | fromjson | .rubygems_api_key') \
		-it \
		ruby:2.5 \
		script/push-gem.sh


clean: ## Cleanup artifacts generated by build.
	@echo "--- :shower: Cleaning up :shower:"
	-rm *.gem

all: build test push
